insert into books (id,isbn,title,author,price) values (1,'isbn-1','title-1','author-1',1.1)
insert into books (id,isbn,title,author,price) values (2,'isbn-2','title-2','author-2',2.2)
insert into books (id,isbn,title,author,price) values (3,'isbn-3','title-3','author-3',3.3)
insert into books (id,isbn,title,author,price) values (4,'isbn-4','title-4','author-4',4.4)
insert into books (id,isbn,title,author,price) values (5,'isbn-5','title-5','author-5',5.5)
